Fix: RemedyModal.tsx style error
The error `src/components/remedies/RemedyModal.tsx(186,14): error TS2322: Type '{ children: string; jsx: true; }' is not assignable to type 'DetailedHTMLProps<StyleHTMLAttributes<HTMLStyleElement>, HTMLStyleElement>'` indicates an issue with how the `style jsx` is being used. This commit will address the error.